### ISSUE TITLE
Bundles delete items when inputed max stack or more

### ISSUE THREAD

**Issue by Foreck1** [ISurrealI/Bundles#2]
In the pack, the max stacks of sizes are set to 128 and 256 for different items/blocks. With Bundles configured to hold up to 128 items, if a single stack of 128 or more items is right-clicked to add to the bundle (either of both input methods), the stack becomes unretrievable and deleted, still making the bundle full and unusable. 
Stack size is increased using [StackUp!](https://www.curseforge.com/minecraft/mc-mods/stackup)
![image](https://github.com/ISurrealI/Bundles/assets/47757429/22d3c4b2-bef5-43a1-9e96-e84fb871eb1e)
clicking a 256 stack:
![image](https://github.com/ISurrealI/Bundles/assets/47757429/f278eefc-c434-4561-865d-f95cddd84ccb)
after clicking:
![image](https://github.com/ISurrealI/Bundles/assets/47757429/be0d884d-7fa9-4aac-b15c-7317e6d879e0)

**Comment by ISurrealI** [comment]
Fixed in [this commit](https://github.com/ISurrealI/Bundles/commit/523e7a63477e5e1addeb14b5f7a08abe065b6627)
